add some code

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,12 +3,23 @@ on: [push]
 jobs:
   cibuild:
     name: cibuild
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-20.04
+    defaults:
+      run:
+        shell: bash
     steps:
       - uses: actions/checkout@v2
-      - uses: actions/setup-go@v2
+      - uses: WillAbides/setup-go-faster@v1
         with:
           go-version: '~1.15.0'
       - run: script/generate --check
       - run: script/test
       - run: script/lint
+      - name: sayhi
+        run: |
+          set -ex
+          got="$(script/sayhi)"
+          if [ "$got" != "his" ]; then
+            echo "::error ::wrong output expected 'hi' but got '$got'"
+            exit 1
+          fi
