definitely need exit 1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,6 +19,7 @@ jobs:
         run: |
           set -ex
           got="$(script/sayhi)"
-          if [ "$got" != "hi2" ]; then
-            echo "::error ::wrong output expected 'hi2' but got '$got'"
+          if [ "$got" != "hi" ]; then
+            echo "::error ::wrong output expected 'hi' but got '$got'"
+            exit 1
           fi
