1.9.0

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,7 +19,7 @@ jobs:
         shell: bash
     steps:
       - uses: actions/checkout@v3
-      - uses: WillAbides/setup-go-faster@v1.8.0
+      - uses: WillAbides/setup-go-faster@v1.9.0
         with:
           go-version: 1.20.x
       - run: script/lint
@@ -34,31 +34,31 @@ jobs:
             echo "::error ::wrong output expected 'hi' but got '$got'"
             exit 1
           fi
-  test-tip:
-    name: test-tip
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - ubuntu-22.04
-          - ubuntu-20.04
-          - windows-2019
-          - macos-11
-    runs-on: ${{ matrix.os }}
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - uses: actions/checkout@v3
-      - uses: WillAbides/setup-go-faster@v1.8.0
-        with:
-          go-version: tip
-      - run: go version
-      - name: sayhi
-        run: |
-          set -ex
-          got="$(script/sayhi)"
-          if [ "$got" != "hi" ]; then
-            echo "::error ::wrong output expected 'hi' but got '$got'"
-            exit 1
-          fi
+#  test-tip:
+#    name: test-tip
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os:
+#          - ubuntu-22.04
+#          - ubuntu-20.04
+#          - windows-2019
+#          - macos-11
+#    runs-on: ${{ matrix.os }}
+#    defaults:
+#      run:
+#        shell: bash
+#    steps:
+#      - uses: actions/checkout@v3
+#      - uses: WillAbides/setup-go-faster@v1.9.0
+#        with:
+#          go-version: tip
+#      - run: go version
+#      - name: sayhi
+#        run: |
+#          set -ex
+#          got="$(script/sayhi)"
+#          if [ "$got" != "hi" ]; then
+#            echo "::error ::wrong output expected 'hi' but got '$got'"
+#            exit 1
+#          fi
